services:
  veramabot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - data/server.env
    volumes:
      - /veramabot:/app/data
    environment:
      - TZ=America/New_York
      - LOCALHOST_IP=ip route show | grep -i default | awk '{ print $3 }'